version: '2'
services:
  elasticsearch:
    build: es
    ports:
     - "19200:9200"
    volumes:
     - ./es/config:/usr/share/elasticsearch/config
  kibana:
    build: kibana
    ports:
      - "15601:5601"
    links:
      - elasticsearch:elasticsearch